src/Model/Config/Communication.php, src/Model/Export/Entity/Article/Fields/CategoryPath.php
- Solves issue: 
Fixes for category paths
Category paths are exported without top parent category :
now: ```Kiteboards```
should be ```Kiteboarding\Kiteboards```
CategoryPaths filter is created in wrong order:
now: ```filterCategoryPathROOT%2FKiteboards=Kiteboarding&filterCategoryPathROOT=Kiteboards```
should be: ```filterCategoryPathROOT=Kiteboarding&filterCategoryPathROOT%2FKiteboarding=Kiteboards```
since in sample data Kiteboards is a child category of Kiteboarding
6.1.3
7.0
=> FFWEB-1332: Data Export - Fix for category paths

src/Model/Config/Communication.php
- Solves issue: #29 
- Description: Add missing values to `ff-communication` component
- Tested with Oxid EShop editions/versions: EE 6.14
- Tested with PHP versions: 7.1
=> Add session data to ff-communication

CHANGELOG.md, src/views/frontend/blocks/scripts.tpl
- Description: on category pages, searchImmediate would push the category filter to the URL history, making the URL very verbose
- Tested with Oxid EShop editions/versions: CE 6.2.0
- Tested with PHP versions: 7.1
=> FFWEB-1855: Exclude category filter from URL on category pages

CHANGELOG.md, src/views/frontend/widget/search.tpl
- Closes #55
- Description: Since the search field was inside of a form, hitting the enter key would trigger a submit. This would also simulate a click event on the `submit` button, probably for event handling. Both events (button click and submit) were triggering events in the library. The HTML was modified by remove the unnecessary form tag and changing the button type to a generic button.
- Tested with Oxid EShop editions/versions: CE 6.2.0
- Tested with PHP versions: 7.1
=> Prevent search event from being triggered twice on result page

CHANGELOG.md, src/views/frontend/blocks/search/result.tpl, src/views/frontend/widget/campaign/feedbacktext.tpl
- Fixes 
Web Components Oxid Module Feedback Text implementation for Bergspetzl
Web Components Oxid Module Feedback Text implementation for Bergspetzl
6.2.4
7.3
=> FFWEB-2084: add feedback-campaigns blocks to search result page

CHANGELOG.md, src/views/frontend/blocks/scripts.tpl
Fix redirection to search result page loses parameters where you are in specific language context (having more than one language enabled)
6.1.3
7.3
=> FFWEB-2098: Fix redirection to search page loses search params

CHANGELOG.md, src/Export/Field/FilterAttributes.php
- Fixes
#74 
Fix error with export handler for FilterAttributes does not handle non-string values properly
6.2.4
7.3
=> FFWEB-2117: Fix error with export handler for FilterAttributes does not handle non-string values properly

src/Model/Config/Communication.php
- Mitigates #77
- Description: recommendation for making the additional currency fields overwritable before final implementation hits
- Tested with Oxid EShop editions/versions: 6.2
- Tested with PHP versions: 7..4
=> recommendation for making the additional currency fields overwritable

src/metadata.php, src/out/admin/css/styles.css, src/views/admin/blocks/factfinder_config_field_ftp_host.tpl, src/views/admin/blocks/factfinder_config_field_server_url.tpl
- Fixes
FFWEB-2167
Add validation for url and frp fields
6.2.4
7.3.28
=> FFWEB-2167: Add HTML5 validation for URL and FTP fields

CHANGELOG.md, composer.json
Declare php8.0 compatibility
6.3
8.0
=> FFWEB-2276: Declare PHP 8.0 compatibility

CHANGELOG.md, src/Model/Config/Communication.php, src/out/js/utils.js, src/views/frontend/blocks/scripts.tpl, src/views/frontend/widget/record_list.tpl
- Fixes
FFWEB-2319
Add scroll to top for category page and search result page after changing page in pagination
6.2.5
7.4.20
=> FFWEB-2319: Add scroll to top for category page and search result page after changing page in pagination

src/Export/CategoryFeed.php, src/Export/Entity/CategoryEntity.php
Export `oxlongdesc` field in category export
EE 6.3.0
8.0
=> FFWEB-2334: Add long description to category export

src/Model/Config/Communication.php
- Fixes
https://jira.omikron.net/browse/FFWEB-2352
Fix customer's error with missing RuntimeException class
6.2.5
- 7.4.20
=> FFWEB-2352: RuntimeException not found 4 0 2

CHANGELOG.md, src/Controller/Admin/ModuleConfiguration.php, src/Export/AbstractFeed.php, src/Model/Config/Export.php
=> FFWEB-2365: Use raw values for attribute titles instead of html decoded

CHANGELOG.md, src/Model/Config/Communication.php
Encode twice `%`, `/` and `+` characters when creates category path filter
6.3 EE
8.0
=> FFWEB-2304 Encoding category path fix

CHANGELOG.md, src/Model/Config/FtpParams.php
- Description:
Fix FtpParams does not return stored configuration
6.3 EE
8.0
=> FFWEB-2422 fix FtpParams does not return stored configuration release/3.x

CHANGELOG.md, src/Model/Config/FtpParams.php
- Description:
Fix FtpParams does not return stored configuration
6.3 EE
8.0
=> FFWEB-2422 fix FtpParams does not return stored configuration release/4.x

CHANGELOG.md, src/views/frontend/widget/asn.tpl
hide the category filter on the category page
6.3 EE
8.0
=> FFWEB-2127: hide category filter on category page

.php-cs-fixer.dist.php, CHANGELOG.md, src/Controller/Admin/ArticleFeedController.php, src/Controller/Admin/ModuleConfiguration.php, src/Controller/Admin/TestConnectionController.php, src/Controller/ArticleFeedController.php, src/Export/Field/Attribute.php, src/Model/Config/Communication.php
Custom `getAttributes` implementation that uses array instead of objects
EE 6.3
7.4, 8.0 CLI
=> FFWEB-2477: Optimize feed performance

CHANGELOG.md, src/Controller/Admin/ModuleConfiguration.php, src/Model/Config/FieldRolesMapper.php
Map Field Roles to the format compatible with Web Components
EE 6.3
7.4
=> FFWEB-2503: map FieldRoles

src/Component/Widget/WebComponent.php, src/Model/Config/Communication.php
- Fixes:
- FFWEB-2615
- Description:
- Removed query and cl=search_result parameters from pages without search results
- 6.4 CE
- 7.4
=> FFWEB-2615 - remove undesired params

CHANGELOG.md, src/Model/Config/Communication.php, src/Subscriber/AfterRequestProcessedEventSubscriber.php
- Fixes:
- FFWEB-2642
- Description:
- Fix user login tracking event
- 6.4 CE
- 7.4, 8.1
=> FFWEB-2642: Fix user login tracking event

src/out/js/tracking.js
- Fixes:
- FFWEB-2673
- Description:
- Send `userId` inside *add to cart* tracking
- 6.4 CE
- 7.4, 8.1
=> FFWEB-2673: Send userId inside "add to cart" tracking

CHANGELOG.md, src/Model/Config/Communication.php, src/metadata.php, src/views/admin/de/ffwebcomponents_lang.php, src/views/admin/en/ffwebcomponents_lang.php, tests/Unit/Export/SuggestCategoryFeed/GenerateTest.php
- Fixes:
- FFWEB-2701
- Description:
- Add disable-cache param in shop configuration and ff-communication
- 6.4 CE
- 7.4 
- 8.1
=> FFWEB-2701: Add disable-cache param in shop configuration and ff-communication

README.md
- Fixes #FFWEB-2949
- Description: Update documentation after create new SDK version
- Tested with Oxid EShop editions/versions:  6.5
- Tested with PHP versions: 7.4
=> FFWEB-2949: Update documentation after create new SDK version
