FACT-Finder-Web-Components/oxid-eshop-module

- src/bin/feed-upload.php
- src/bin/feed-write.php
- src/out/css/styles.css
Added cursor pointer to clickable elements
> Added cursor pointer to clickable elements

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
Added github pull request template
> Added github pull request template

- src/Model/ArticleFeed.php
Extracts the declaration which field modifiers are used into another function so integrations can easily add their own modifier through extending only this simply method and adding or modifying the array.
> allow easier modification of used field modifiers

- src/Model/ArticleFeed.php
- src/Model/Config/Communication.php
- src/metadata.php
Add search params option wasn't working. I changed this field to aarr and allow user to define any of allowed parameters
6.1.3
7.1
**Please note that the source and target branch must be `master`**
> FFWEB-1740: Add merge parameters

- src/Controller/ArticleFeedController.php
- src/Model/ArticleFeed.php
- src/Model/Export/FtpClient.php
- src/bin/feed-upload.php
- src/bin/feed-write.php
- Solves issue: #25 
- Description: Handle different shop ID in product exports
- Tested with Oxid EShop editions/versions: CE 6.2 / EE 6.1.4
- Tested with PHP versions: 7.1
**Please note that the source and target branch must be `master`**
> Multishop Product Export

- CHANGELOG.md
- README.md
- src/Model/Config/Communication.php
- src/out/js/tracking.js
- src/views/frontend/blocks/campaign/product.tpl
Implements cart tracking using Web Components API
6.1.3
7.3
> FFWEB-2104: Implement Cart Tracking

- .github/workflows/ci.yml
- .php-cs-fixer.dist.php
- composer.json
- src/Contract/Config/ParametersSourceInterface.php
- src/Controller/Admin/ModuleConfiguration.php
- src/Export/Entity/DataProvider.php
- src/Export/Entity/DataProviderInterface.php
- src/Export/Entity/ExportEntityInterface.php
- src/Export/ExporterInterface.php
- src/Export/Field/CategoryPath.php
- src/Export/Field/FieldInterface.php
- src/Export/Field/FilterAttributes.php
- src/Export/Filter/FilterInterface.php
- src/Export/Stream/StreamInterface.php
- src/Model/Config/Authorization.php
- src/Model/Config/Communication.php
- src/Model/Export/FtpClient.php
- src/Model/Export/Http/Authentication.php
- src/metadata.php
Introduced php-cs-fixer
6.1.3
7.4
> introduce CS Fixer

- CHANGELOG.md
- src/Model/Config/Communication.php
- Fixes # 
[FFWEB-2304](https://jira.omikron.net/browse/FFWEB-2304)
Implement category-page in Oxid
CE 6.3.1
7.4.20
> FFWEB-2304: remove category filter and navigation true from add params (for NG)

- CHANGELOG.md
- src/Export/Field/FilterAttributes.php
> FFWEB-2409: export attributes from variant level

- CHANGELOG.md
- src/views/frontend/blocks/scripts.tpl
> FFWEB-2483: Assign $oConfig if not set

- src/Subscriber/BeforeHeadersSendEventSubscriber.php
- src/out/js/tracking.js
- src/views/frontend/blocks/campaign/product.tpl
- Fixes:
- FFWEB-2639
- Description:
- Cart tracking fix
- 6.4 CE
- 7.4
> FFWEB-2639 - cart tracking fix

- CHANGELOG.md
- composer.json
- src/metadata.php
- src/out/js/tracking.js
- src/views/frontend/blocks/campaign/product.tpl
- src/views/frontend/blocks/page/details/inc/productmain.tpl
- src/views/smarty/modifier.record_data_json.php
- Fixes:
- FFWEB-2651
- FFWEB-2652
- Description:
- Fix tracking for add to cart event
- Replace getRecords event with object served from backend
- 6.4 CE
- 7.4
> FFWEB-2651: Fix tracking for add to cart event

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- composer.json
- src/Export/Data/ArticleCollection.php
- src/Export/Data/CategoryCollection.php
- src/Export/Entity/ArticleEntity.php
- src/Export/Entity/CategoryEntity.php
- src/Export/Field/Attribute.php
- src/Export/Field/Category/SourceField.php
- src/Model/Api/PushImport.php
- src/Model/Config/Communication.php
- src/Model/Config/Export.php
- src/Model/Config/FtpParams.php
- src/Model/Export/FtpClient.php
- src/Model/Export/Http/Authentication.php
- src/Model/Export/SftpClient.php
- src/Model/Export/UploadFactory.php
- src/Subscriber/AfterRequestProcessedEventSubscriber.php
- src/Subscriber/BeforeHeadersSendEventSubscriber.php
- Description: Update PHP version from 7.4 to 8.1
- Tested with Oxid EShop editions/versions: 7.0
- Tested with PHP versions: 8.1
> FFWEB-2858: Update PHP version from 7.4 to 8.1

- assets/admin/css/styles.css
- metadata.php
- views/twig/admin/ajax_result.html.twig
- views/twig/extensions/themes/admin_twig/module_config.html.twig
- Fixes FFWEB-2861
- Description: Rewrite admin templates from smarty to twig
- Tested with Oxid EShop editions/versions: 7.0
- Tested with PHP versions: 8.1
> FFWEB-2861: Rewrite admin templates from smarty to twig

- metadata.php
- src/Controller/Admin/ArticleFeedController.php
- src/Controller/Admin/TestConnectionController.php
- src/Export/AbstractFeed.php
- src/Export/Field/Attribute.php
- src/Export/Field/FilterAttributes.php
- src/Export/Filter/ExtendedTextFilter.php
- src/Export/Filter/TextFilter.php
- src/Model/Config/FtpParams.php
- views/twig/extensions/themes/admin_twig/module_config.html.twig
- Fixes FFWEB-2934
- Description: Fix Test connection API/FTP features
- Tested with Oxid EShop editions/versions: 7.0 CE
- Tested with PHP versions: 8.1
> FFWEB-2934: Fix Test connection API/FTP features

- metadata.php
- src/Controller/SearchResultController.php
- src/Core/ViewConfig.php
- src/Model/Config/Communication.php
- src/bin/feed-write.php
- views/twig/extensions/themes/default/layout/base.html.twig
- views/twig/extensions/themes/default/layout/page.html.twig
- views/twig/extensions/themes/default/widget/header/search.html.twig
- views/twig/webcomponents/blocks/page/result.html.twig
- views/twig/webcomponents/widget/communication.html.twig
- views/twig/webcomponents/widget/suggest.html.twig
- Fixes FFWEB-2861
- Description: Rewrite templates to Twig (part I)
> FFWEB-2861: Rewrite templates to Twig (part I)

- src/Model/Config/Communication.php
- views/admin_twig/blocks/factfinder_config_field_api_version.html.twig
- views/admin_twig/blocks/factfinder_config_field_ftp_key.html.twig
- views/twig/extensions/themes/default/page/checkout/basket.html.twig
- views/twig/extensions/themes/default/page/details/inc/productmain-todo.html.twig
- views/twig/extensions/themes/default/page/list/list.html.twig
- views/twig/webcomponents/blocks/page/result.html.twig
- views/twig/webcomponents/blocks/search/result.html.twig
- views/twig/webcomponents/widget/asn.html.twig
- views/twig/webcomponents/widget/breadcrumbs.html.twig
- views/twig/webcomponents/widget/campaign/feedbacktext.html.twig
- views/twig/webcomponents/widget/campaign/pushed_products.html.twig
- views/twig/webcomponents/widget/campaign/search_advisor.html.twig
- views/twig/webcomponents/widget/paging.html.twig
- views/twig/webcomponents/widget/ppp.html.twig
- views/twig/webcomponents/widget/record_list.html.twig
- views/twig/webcomponents/widget/result_count.html.twig
- views/twig/webcomponents/widget/sortbox.html.twig
Rewrite templates to Twig (part II)
> FFWEB-2861: Rewrite templates to Twig (part II)

- src/Controller/Admin/ModuleConfiguration.php
- views/twig/extensions/themes/admin_twig/module_config.html.twig
Fix and improve update fields roles feature
> FFWEB-2937: Fix and improve update fields roles feature

- src/Controller/SearchResultController.php
- src/Model/Api/PushImport.php
- src/Model/Config/Authorization.php
Fix and improve automatic import feature
> FFWEB-2940: Fix and improve automatic import feature

- assets/css/styles.css
- views/twig/extensions/themes/default/layout/sidebar.html.twig
- views/twig/extensions/themes/default/page/list/list.html.twig
Implement Using FACT-Finder® on category pages
> FFWEB-2941: Implement Using FACT-Finder® on category pages

- metadata.php
- views/twig/extensions/themes/default/page/checkout/basket.html.twig
- views/twig/extensions/themes/default/page/details/inc/related_products.html.twig
- views/twig/webcomponents/widget/campaign/search_advisor.html.twig
- views/twig/webcomponents/widget/recommendation.html.twig
- views/twig/webcomponents/widget/similar.html.twig
Implement campaigns for PDP and cart
> FFWEB-2942: Implement campaigns for PDP and cart

- views/twig/extensions/themes/default/page/checkout/thankyou.html.twig
- views/twig/extensions/themes/default/page/details/inc/productmain-todo.html.twig
Implement ff-checkout-tracking on TYP
> FFWEB-2943: Implement ff-checkout-tracking on TYP

- src/Controller/Admin/ModuleConfiguration.php
- src/Export/AbstractFeed.php
- src/Export/Entity/ArticleEntity.php
- src/Model/Config/Export.php
- views/admin_twig/en/ffwebcomponents_en_lang.php
Add support for attributes export
> FFWEB-2944: Add support for attributes export

- src/Model/Config/Communication.php
- views/twig/extensions/themes/default/layout/sidebar.html.twig
- views/twig/extensions/themes/default/page/details/inc/productmain.html.twig
- views/twig/extensions/themes/default/page/details/inc/related_products.html.twig
- views/twig/extensions/themes/default/page/list/list.html.twig
- views/twig/webcomponents/widget/communication.html.twig
- Fix category pages ASN and navigation request
- Fix cart tracking
- Fix similar and recommendation items on PDP
> FFWEB-2948: Bug fixes after QA tests

- CHANGELOG.md
- README.md
Update SDK documentation and changelog
> FFWEB-2950: Update SDK documentation and changelog

- metadata.php
- src/Controller/Admin/ArticleFeedController.php
- src/Controller/Admin/TestConnectionController.php
- src/Core/ViewConfig.php
- src/Export/Field/Attribute.php
- src/Model/Config/Authorization.php
- src/Model/Config/Communication.php
- src/Model/Config/FtpParams.php
- src/Subscriber/BeforeHeadersSendEventSubscriber.php
- src/Twig/Extensions/Filters/RecordDataJson.php
- src/bin/feed-upload.php
- src/bin/feed-write.php
- tests/Unit/Export/Exporter/ExportEntitiesTest.php
- tests/Unit/Export/Field/Category/CategoryPathTest.php
- tests/Unit/Export/Field/Category/DeeplinkTest.php
- tests/Unit/Export/Field/Category/ParentCategoryTest.php
- tests/Unit/Export/Field/Category/SourceFieldTest.php
- tests/Unit/Export/SuggestCategoryFeed/GenerateTest.php
- tests/Unit/Subscriber/AfterRequestProcessedEventSubscriber/hasJustLoggedInTest.php
- tests/Unit/Subscriber/AfterRequestProcessedEventSubscriber/hasJustLoggedOutTest.php
- tests/Unit/Subscriber/BeforeHeadersSendEventSubscriber/HasJustLoggedInTest.php
- tests/Variant/Export/Stream/CsvVariant.php
> FFWEB-2951: Fix Coding Standards Fixer
